name: CMake Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -S ./tests -B ./tests/build
    - name: Build
      run: cmake --build tests/build
    - name: Run Tests
      run: |
        ./tests/build/tests